version: "2"
linters:
  enable:
    - errcheck
    - gosec
    - misspell
    - revive
    - staticcheck
    - govet
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - revive
        path: internal/mocks
      - linters:
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - revive
        path: cmd
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
